id: I4CEA942E
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T14:16:47.465041'
last_modified: '2022-06-17T14:16:47.465065'
parser: null
source_metadata:
  title: Sojong Series
  language: bo
  description: 'Texts on the theme of Poṣadha or Sojong (''healing and purification'')
    practice:'
  volume:
    f44C0:
      title: The Method for Observing the Eight-Branched One-Day Vow
      base_file: f44C0.txt
      order: 1
      parent: Explanation
    f4D1E:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      base_file: f4D1E.txt
      order: 2
      parent: Practices
    fDCBA:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      base_file: fDCBA.txt
      order: 3
      parent: Practices
    fAADD:
      title: Taking the Vows of Sojong
      base_file: fAADD.txt
      order: 4
      parent: Practices
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
